### PR TITLE
fix CRLF issues in windows

### PR DESCRIPTION
**Pull request by ssrlive**
avoid rewriting same sorted file and fix newline issues in windows.

### CODE REVIEW

**Comment by DevinR528** [comment]
Hey, sorry it takes me so long to respond! Thanks for the PR. Could you resolve the conflicts then I can take a look. From what I see this seems like a good change.

**Comment by ssrlive** [comment]
Done
> Hey, ... Could you resolve the conflicts ...

**Comment by ssrlive** [comment]
Please publishing a new version that we can use it immediately.

**Comment by ssrlive** [comment]
click

**Comment by ssrlive** [comment]
beep

**Comment by ssrlive** [comment]
beep

**Comment by ssrlive** [comment]
beep

**Comment by ssrlive** [comment]
beep

**Comment by ssrlive** [comment]
beep

**Comment by ssrlive** [comment]
beep

**Comment by ssrlive** [comment]
beep

**Comment by ssrlive** [comment]
beep

**Comment by ssrlive** [comment]
Hi @jplatte , can you merge the PR and publish a new version?

**Review by jplatte — APPROVED** [review]

**Comment by jplatte** [comment]
Hey, so I published this but unfortunately other changes since 1.0.9 broke too many things that used to work. I have yanked the new release, not sure when I'll get back to this.

**Pull request merged**
